"use client";

import React, { useState, useRef, useEffect } from "react";
import Header from "../../components/Header/Header";

const Privacy = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [selectedLanguage, setSelectedLanguage] = useState("Select Language");
  const dropdownRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  return (
    <div
      className="min-h-screen text-white font-sans bg-cover bg-center">
      <Header />

      {/* Top Info Section */}
      <div className="flex flex-col items-center justify-center mt-18 text-center px-4 pt-12 pb-16">

        {/* Dates & Title */}
        <p className="text-sm text-[#F4F4F4] -mt-2 mb-2">Published: 18 April, 2025</p>
        <h1 className="text-6xl font-extrabold mt-2 mb-2">Privacy policy</h1>
        <p className="text-md text-[#F4F4F4] mb-6 mt-2">
          Effective: April 18, 2025 (previous version)
        </p>

        {/* Intro Paragraph */}
        <p className="max-w-[800px] text-gray-200 text-left mt-20 ml-[110px] text-lg">
        At Voyex, we are committed to protecting your privacy. This Privacy Policy explains how we handle your information when you use our platform.
        </p>
      </div>

         {/* Terms Content */}
         <div className="max-w-[760px] mx-auto px-10 py-12 space-y-10 -mt-10 text-gray-200">
  <div className="space-y-4">
    <h2 className="text-3xl font-bold ml-4">1. Information we collect</h2>
    <p>
      We collect limited information to improve your experience, such as:
    </p>
    <ul className="list-disc pl-6 space-y-2">
      <li>Queries or inputs submitted on the platform</li>
      <li>Browser/device metadata (for performance & analytics)</li>
      <li>Optional user feedback or tool bookmarks (if logged in)</li>
    </ul>
    <p>
      We do not collect or store any sensitive personal information (e.g., passwords, financial data) unless explicitly stated.
    </p>
  </div>

  <div className="space-y-4">
    <h2 className="text-3xl font-bold ml-4">2. How We Use Your Data</h2>
    <ul className="list-disc pl-6 space-y-2">
      <li>To personalize tool recommendations</li>
      <li>To improve platform functionality and user experience</li>
      <li>To monitor traffic and usage trends (via analytics services)</li>
    </ul>
  </div>

  <div className="space-y-4">
    <h2 className="text-3xl font-bold ml-4">3. Third–Party Tools and Services</h2>
    <p>
      Voyex recommends and links to third–party AI tools. We <em><strong>do not control, operate, or take responsibility</strong></em> for these external services.
    </p>
    <p>When you visit or use a tool listed on Voyex:</p>
    <ul className="list-disc pl-6 space-y-2">
      <li>You are subject to that tool&apos;s own privacy policy and terms</li>
      <li>Voyex does not store your data, prompts, or outputs sent to third–party platforms</li>
      <li>We are not liable for any data handling or content generated by those tools</li>
    </ul>
  </div>

  <div className="space-y-4">
    <h2 className="text-3xl font-bold ml-4">4. Data Security</h2>
    <p>
      We follow best practices to protect any non–sensitive data we store. However, you are responsible for verifying the security and compliance of any third–party tool you choose to use.
    </p>
  </div>

  <div className="space-y-4">
    <h2 className="text-3xl font-bold ml-4">5. Your Rights</h2>
    <p>
      If you wish to access, delete, or request more information about your data (if applicable), please contact us at  [voyex.outreach@gmail.com]
    </p>
  </div>
</div>

      </div>
  );
};

export default Privacy;
